ADDR_SCS_TORQUE_ENABLE     = 40
ADDR_STS_GOAL_ACC          = 41
ADDR_STS_GOAL_POSITION     = 42
ADDR_STS_GOAL_SPEED        = 46
ADDR_STS_PRESENT_POSITION  = 56

SCS_MINIMUM_POSITION_VALUE  = 100
SCS_MAXIMUM_POSITION_VALUE  = 4000
SCS_MOVING_STATUS_THRESHOLD = 20
SCS_MOVING_SPEED            = 0
SCS_MOVING_ACC              = 0